demotwitter3/config/routes.rb
Rails.application.routes.draw do
  
  resources :messages
  get 'welcome/index'

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  resources :users do 
    member do
      get :following,:followers
    end
  end
  resources :relationships

  resources :posts do
    get 'images', on: :collection
    resources :comments
  end
  resources :retweets
  root 'welcome#index'

end

demotwitter3/app/controllers/retweets_controller.rb
class RetweetsController < ApplicationController

  def show
    @retweet = Post.find(params[:id])
    @post = Post.find(@retweet.retweet_id)
  end

  def new
    @post = Post.find(params[:id])
    @retweet = @post.retweets.build
    respond_to do |format|
      format.html
      format.js
    end    
  end

  def create
    @post = Post.find(params[:id])
    @retweet = @post.retweets.build(retweet_params)
    @posts = Post.all
    if @retweet.save
      respond_to do |format|
        format.html { redirect_to retweet_path(@retweet) }
        format.js 
      end
    else
      render 'new'
    end
  end

  private

  def retweet_params
    params.require(:post).permit(:retweet_id, :content, :avatar).merge(user_id: current_user.id)
  end
  
end

demotwitter3/app/helpers/retweets_helper.rb
module RetweetsHelper
end

demotwitter3/app/views/retweets/_form.html.erb
<%= form_for @retweet, url: retweets_path(id: @post.id),remote: true do |f| %>
  <%= f.text_area :content, size: "80x5",style: 'border-radius: 10px;' %>
  <br><br>
  <%= f.submit "Retweet", class: 'btn btn-primary' %>
<% end %>

demotwitter3/app/views/retweets/_index.html.erb
<% @posts.each do |post| %>
  <div id="show-post-timeline">
    <span class="name"><%= link_to post.user.name.capitalize, user_path(post.user) %></span> 
    @<%= post.user.username %> 
    <span class="time"><%= time_ago_in_words(post.created_at) %></span>
    <br>
    <h4>&nbsp<%= post.content %></h4>
    <% if post.avatar.url.present? %>
      <p><%= image_tag(post.avatar.url,style: 'border: 1px solid black;width: 300px;height: 200px;margin-top: 10px;margin-left: 10px;margin-bottom: 14px;', class: 'img-rounded') %></p>
    <% end %>
    <% if post.retweet_id.present? %>
      <% @retweet = Post.find(post.retweet_id) %>
      <br>
      <div class="panel panel-default">
        <div class="panel-body">
          <span class="name"><%= link_to @retweet.user.name.capitalize, user_path(@retweet.user) %></span> 
          @<%= @retweet.user.username %> 
          <span class="time"><%= time_ago_in_words(@retweet.created_at) %></span>
          <br>
          <h4>&nbsp<%= @retweet.content %></h4>
          <% if @retweet.avatar.url.present? %>
            <p><%= image_tag(@retweet.avatar.url,style: 'border: 1px solid black;width: 150px;height: 80px;margin-top: 10px;margin-left: 10px;margin-bottom: 14px;', class: 'img-rounded') %></p>
          <% end %>
        </div>
      </div>
    <% end %>
  <div id="retweet-<%= post.id %>">
    <% if post.retweets.present? %>
      <span class="count"><%= post.retweets.count %></span>
    <% end %>
    <%= link_to(new_retweet_path(id: post),remote: true) do %>
      <i class="glyphicon glyphicon-retweet" style="color:blue"></i>
      <span style="color:blue">Retweet</span>
    <% end %>
    &nbsp
    <% if post.comments.present? %>
      <%= link_to post.comments.count, post_comments_path(post),class: "count",style: "text-decoration: none" %><% end %> 
      <%= link_to(new_post_comment_path(post)) do %>
      <i class="glyphicon glyphicon-comment" style="color:green"></i> 
      <span style="color:green">Comment</span>
    <% end %>
    <% if post.user_id == current_user.id %>
      &nbsp
      <%= link_to post_path(post), method: :delete, data: {confirm: "Are you sure?"}, remote: true do %>
      <i class="glyphicon glyphicon-trash" style="color:red"></i>
      <span style="color:red">Delete</span>
    <% end %>
  <% end %>
  </div>
  <hr>
  </div>
<% end %>

demotwitter3/app/views/retweets/create.js.erb
$('#retweet-<%= @post.id %>').slideUp(350);
$('#retweets').html('');
$("#retweets").html("<%= j (render 'retweets/index') %>");

demotwitter3/app/views/retweets/new.html.erb
<div class="col-sm-3">
  <div class = "panel panel-info">
    <div class = "panel-heading">
      <h4>Your Twitter Profile</h4>
    </div>
      <div class = "panel-body">
      <br>
        <% if current_user.avatar.url.present? %>
        <%= image_tag(current_user.avatar.url(:thumb), class: 'img-rounded') %>
        <% else %>
        <%= image_tag('default.png',size: '100x100',class: 'img-rounded') %>
        <% end %>
        <h4><span class="name"><%= current_user.name.capitalize %></span> @<%= current_user.username %></h4>
        <br>
        <table class = "table table-bordered">
          <tr>
            <td><%= link_to 'Tweets' ,post_path(current_user) %></td>
            <td><%= link_to 'Followers',followers_user_path(current_user) %></td>
            <td><%= link_to 'Following',following_user_path(current_user) %></td>
          </tr>
            <tr class = "success">
            <td><%= current_user.posts.size %></td>
            <td><%= current_user.followers.count%></td>
            <td><%= current_user.following.count%></td>
          </tr>
        </table>
    </div>
    </div>
</div>
<div class="col-sm-7">
  <div class="panel panel-info">
    <div class="panel-heading">
      <h4>Retweet</h4>
    </div>
    <div class="panel-body">
      <%= form_for @retweet, url: retweets_path(id: @post.id) do |f| %>
        <%= f.text_area :content, size: "80x5",style: 'border-radius: 10px;' %>
        <br><br>
        <%= f.file_field :avatar %>
        <%= f.hidden_field :avatar_cache %>
        <br>
        <%= f.submit "Retweet", class: 'btn btn-primary' %>
      <% end %>
    </div>
    <div class="panel-heading">
      <h4>Tweet</h4>
    </div>
    <div class="panel-body">
      <span class="name"><%= link_to @post.user.name.capitalize, user_path(@post.user) %></span> 
        @<%= @post.user.username %> 
        <span class="time"><%= time_ago_in_words(@post.created_at) %></span>
        <br>
        <h4>&nbsp<%= @post.content %></h4>
        <% if @post.avatar.url.present? %>
        <p><%= image_tag(@post.avatar.url,style: 'width: 250px;height: 150px;margin-top: 10px;margin-left: 10px;margin-bottom: 14px;', class: 'img-rounded') %></p>
        <% end %>
        &nbsp
        <%= link_to(new_post_comment_path(@post)) do %>
        <i class="glyphicon glyphicon-comment" style="color:green"></i> 
        <span style="color:green">Comment</span>
        <% end %>
        <% if @post.user_id == current_user.id %>
        &nbsp
        <%= link_to post_path(@post), method: :delete, data: {confirm: "Are you sure?"}, remote: true do %>
          <i class="glyphicon glyphicon-trash" style="color:red"></i>
          <span style="color:red">Delete</span>
        <% end %>
        <% end %>
    </div>
  </div>
</div>

demotwitter3/app/views/retweets/new.js.erb
$('#retweet-<%= @post.id %>').html("<%= j (render 'form') %>");
$('#retweet-<%= @post.id %>').slideDown(350);

demotwitter3/app/views/retweets/show.html.erb
<div class="col-sm-3">
  <div class = "panel panel-info">
    <div class = "panel-heading">
      <h4>Your Twitter Profile</h4>
    </div>
      <div class = "panel-body">
      <br>
        <% if current_user.avatar.url.present? %>
        <%= image_tag(current_user.avatar.url(:thumb), class: 'img-rounded') %>
        <% else %>
        <%= image_tag('default.png',size: '100x100',class: 'img-rounded') %>
        <% end %>
        <h4><span class="name"><%= current_user.name.capitalize %></span> @<%= current_user.username %></h4>
        <br>
        <table class = "table table-bordered">
          <tr>
            <td><%= link_to 'Tweets' ,post_path(current_user) %></td>
            <td><%= link_to 'Followers',followers_user_path(current_user) %></td>
            <td><%= link_to 'Following',following_user_path(current_user) %></td>
          </tr>
            <tr class = "success">
            <td><%= current_user.posts.size %></td>
            <td><%= current_user.followers.count%></td>
            <td><%= current_user.following.count%></td>
          </tr>
        </table>
    </div>
    </div>
</div>
<div class="col-sm-7">
  <div class="panel panel-info">
    <div class="panel-heading">
      <h4>Retweet</h4>
    </div>
    <div class="panel-body">
      <span class="name"><%= link_to @retweet.user.name.capitalize, user_path(@retweet.user) %></span> 
        @<%= @retweet.user.username %> 
        <span class="time"><%= time_ago_in_words(@retweet.created_at) %></span>
        <br>
        <h4>&nbsp<%= @retweet.content %></h4>
        <% if @retweet.avatar.url.present? %>
        <p><%= image_tag(@retweet.avatar.url,style: 'width: 150px;height: 100px;margin-top: 10px;margin-left: 10px;margin-bottom: 14px;', class: 'img-rounded') %></p>
        <% end %>
        <br>
          <div class="panel panel-default">
            <div class="panel-body">
            <span class="name"><%= link_to @post.user.name.capitalize, user_path(@post.user) %></span> 
            @<%= @retweet.user.username %> 
            <span class="time"><%= time_ago_in_words(@post.created_at) %></span>
            <br>
            <h4>&nbsp<%= @post.content %></h4>
            <% if @post.avatar.url.present? %>
            <p><%= image_tag(@post.avatar.url,style: 'width: 150px;height: 100px;margin-top: 10px;margin-left: 10px;margin-bottom: 14px;', class: 'img-rounded') %></p>
            <% end %>
            </div>
          </div>
        <%= link_to(new_retweet_path(id: @retweet)) do %>
          <i class="glyphicon glyphicon-retweet" style="color:blue"></i>
          <span style="color:blue">Retweet</span>
        <% end %>&nbsp
        <%= link_to(new_post_comment_path(@retweet)) do %>
        <i class="glyphicon glyphicon-comment" style="color:green"></i> 
        <span style="color:green">Comment</span>
        <% end %>&nbsp
        <% if @post.user_id == current_user.id %>
        <%= link_to post_path(@retweet), method: :delete, data: {confirm: "Are you sure?"}, remote: true do %>
          <i class="glyphicon glyphicon-trash" style="color:red"></i>
          <span style="color:red">Delete</span>
        <% end %>
        <% end %>
    </div>
  </div>
</div>