demo2/config/routes.rb
Rails.application.routes.draw do
  resources :students
  root 'students#index'

end

demo2/app/models/student.rb
class Student < ActiveRecord::Base
	#validates :student_name, presence: true
	validates :Age, presence: true
	validates :terms_of_service, acceptance: { accept: true }
	validates :email, presence: true, confirmation: true, uniqueness: true
	validates :email_confirmation, presence: true
	validates :pincode, length: { is: 6 , message: 'is of wrong length (should contain 6 numeric)' }
	
	before_create do
		self.student_name = student_name.capitalize unless student_name.blank?
	end

 	before_validation :ensure_name_has_a_value
 	protected
	def ensure_name_has_a_value
		if student_name.empty?
			self.student_name = email unless email.blank?
		end	
	end
	after_validation :change_student_name
	protected 
	def change_student_name
		if student_name.present?
			self.student_name = 'Vishal'
		end
	end
end

demo2/app/controllers/aa.rb
n = 4
i = 1
for n in n.downto(i)
	for k in (n*2-1)..(n*3-1)
		print k
	end
	puts
end

demo2/app/controllers/students_controller.rb
class StudentsController < ApplicationController
	def index
		@students = Student.all
	end

	def new
		@student = Student.new
	end

	def edit
		@student = Student.find(params[:id])
	end

	def show
		@student = Student.find(params[:id])
	end

	def create
		@student = Student.new(student_params)
		if @student.save
			redirect_to @student
		else
			render 'new'
		end
	end

	def update
		@student = Student.find(params[:id])
		if @student.update(student_params)
			redirect_to @student
		else
			render 'edit'
		end
	end

	def destroy
		@student = Student.find(params[:id])
		@student.destroy
		redirect_to students_path
	end

	private
	def student_params
		params.require(:student).permit( :student_name, :Age,
		 :terms_of_service, :email, :email_confirmation, :pincode)
	end
end

demo2/app/helpers/students_helper.rb
module StudentsHelper
end

demo2/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Demo2</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

demo2/app/views/students/edit.html.erb
<h1>Student</h1>
<%= form_for @student do |f| %>

<% if @student.errors.any? %>
	<div id="error_message">
	<h2><%= pluralize(@student.errors.count,'error') %> Prohibited this details from being saved:
	</h2>
	<ul>
		<% @student.errors.full_messages.each do |msg| %>
		<li><%= msg %></li>
		<% end %>
	</ul>
	</div>
<% end %>
<p>
	<%= f.label :Student_Name %>
	<%= f.text_field :student_name %>
</p>
<p>
	<%= f.label :Age %>
	<%= f.number_field :Age %>
</p>
<p>
	<%= f.label :email %>
	<%= f.email_field :email %>
</p>
<p>
	<%= f.label :email_confirmation %>
	<%= f.email_field :email_confirmation %>
</p>
<p>
	<%= f.label :pincode %>
	<%= f.text_field :pincode %>
</p>
<p>
	<%= f.check_box :terms_of_service %>
	Accept terms and condition
</p>

<p>
	<%= f.submit %>
</p>
<% end %>

demo2/app/views/students/index.html.erb
<h1>Student Page</h1>
<%= link_to 'Enter Details', new_student_path %>
<table>
	<tr>
		<th>Name</th>
		<th>Age</th>
		<th>Email</th>
		<th>Pincode</th>
	</tr>
	<% @students.each do |f| %>
	<tr>
		<td><%= f.student_name %></td>
		<td><%= f.Age %></td>
		<td><%= f.email %></td>
		<td><%= f.pincode %></td>
		<td><%= link_to 'Show', student_path(f)%></td>
		<td><%= link_to 'Edit', edit_student_path(f)%></td>
		<td><%= link_to 'Delete', student_path(f),method: :delete,data: 
		{ confirm: 'Are you sure' } %></td>
	</tr>
	<% end %>
</table>

demo2/app/views/students/new.html.erb
<h1>Student</h1>
<%= form_for @student do |f| %>

<% if @student.errors.any? %>
	<div id="error_message">
	<h2><%= pluralize(@student.errors.count,'error') %> Prohibited this details from being saved:
	</h2>
	<ul>
		<% @student.errors.full_messages.each do |msg| %>
		<li><%= msg %></li>
		<% end %>
	</ul>
	</div>
<% end %>
<p>
	<%= f.label :student_name %>
	<%= f.text_field :student_name %>
</p>
<p>
	<%= f.label :Age %>
	<%= f.number_field :Age %>
</p>
<p>
	<%= f.label :email %>
	<%= f.email_field :email %>
</p>
<p>
	<%= f.label :email_confirmation %>
	<%= f.email_field :email_confirmation %>
</p>
<p>
	<%= f.label :pincode %>
	<%= f.text_field :pincode %>
</p>
<p>
	<%= f.check_box :terms_of_service %>
	Accept terms and condition
</p>
<p>
	<%= f.submit %>
</p>
<% end %>

demo2/app/views/students/show.html.erb
<h1>Student Detail</h1>
<p>
	<strong>Name:</strong>
	<%= @student.student_name %>
	<strong>Age:</strong>
	<%= @student.Age %>
	<strong>Email:</strong>
	<%= @student.email %>
	<strong>Pincode:</strong>
	<%= @student.pincode %>
</p>
<%= link_to 'Index', students_path %>