EShopping/config/routes.rb
Rails.application.routes.draw do
  get 'reports/sales_report'

  get 'reports/customer_register'

  get 'reports/coupon_used'

  resources :contacts, only: [ :index, :edit, :create, :update]
  resources :wish_lists, only: [ :index, :create, :destroy]
  resources :addresses, except: [ :show, :destroy]
  resources :check_outs, only: [ :index]
  get 'review_payment', to: 'check_outs#review_payment'
  resources :cart_items, except: [ :show, :new, :edit]
  get 'remove_coupon', to: 'cart_items#remove_coupon'
  get 'apply_coupon', to: 'cart_items#apply_coupon' 
  resources :categories, only: :show do 
    resources :brands, only: [ :show]
  end
  resources :brands, only: [ :index]
  resources :products, only: :show
  resources :orders, except: [ :new, :edit, :update, :destroy] do 
    member do
      get 'payment'
      post 'create_charges'
      get 'cancel_order'
    end
  end
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  get 'home/index'
  root 'home#index'
  get '*unmatched_route' => 'application#routing_error'

end

EShopping/app/models/address.rb
class Address < ActiveRecord::Base
  belongs_to :user
end

EShopping/app/models/banner.rb
class Banner < ActiveRecord::Base
  mount_uploader :avatar, AvatarUploader
  has_many :pictures, as: :imageable
end

EShopping/app/models/brand.rb
class Brand < ActiveRecord::Base
  has_many :brand_categories, dependent: :destroy
  has_many :categories,through: :brand_categories
  has_many :products, dependent: :destroy
end

EShopping/app/models/cart_item.rb
class CartItem < ActiveRecord::Base
  belongs_to :user
  belongs_to :product

  def self.calculate_total(cart_items,coupon)
    @coupon = Coupon.find_by(code: coupon)
    sub_total = 0
    cart_items.each do |item|
      sub_total += item.quantity * item.product.price
    end
    if @coupon.present?
      discount = (sub_total * @coupon.percent.to_i)/100
    else
      discount = 0
    end
    cart_total = sub_total - discount
    if cart_total < 5000
      shipping_cost = 50.to_f
    else
      shipping_cost = 0.to_f
    end
    [sub_total,shipping_cost,discount,cart_total]
  end
end

EShopping/app/models/category.rb
class Category < ActiveRecord::Base
  has_many :brand_categories, dependent: :destroy
  has_many :brands,through: :brand_categories
  has_many :sub_categories, class_name: "Category", foreign_key: "parent_id"
  belongs_to :parent, class_name: "Category"
  has_many :product_categories, dependent: :destroy
  has_many :products,through: :product_categories
end

EShopping/app/models/check_out.rb
class CheckOut < ActiveRecord::Base
end

EShopping/app/models/contact.rb
class Contact < ActiveRecord::Base
end

EShopping/app/models/coupon.rb
class Coupon < ActiveRecord::Base
end

EShopping/app/models/coupon_used.rb
class CouponUsed < ActiveRecord::Base
  belongs_to :user
  belongs_to :order
  belongs_to :coupon
end

EShopping/app/models/order.rb
class Order < ActiveRecord::Base
  belongs_to :user
  belongs_to :address
  has_many :order_items, dependent: :destroy
  has_many :track_orders, dependent: :destroy
  default_scope { order(:created_at => :desc) }
  has_one :used_coupon
  after_update :track_order_list

  scope :month, -> { Order.all.group_by{ |order| order.created_at.strftime('%B') } }

  def track_order_list
    self.track_orders.create(status: status)
  end
end

EShopping/app/models/order_item.rb
class OrderItem < ActiveRecord::Base
  belongs_to :order
  belongs_to :product
  belongs_to :user
end

EShopping/app/models/picture.rb
class Picture < ActiveRecord::Base
  mount_uploader :avatar, AvatarUploader
  belongs_to :imageable, polymorphic: true
end

EShopping/app/models/product.rb
class Product < ActiveRecord::Base
  has_many :pictures, as: :imageable
  belongs_to :brand
  has_many :product_categories
  has_many :categories,through: :product_categories
  has_and_belongs_to_many(:products,
    :join_table => "recommended_products",
    :foreign_key => "product_id",
    :association_foreign_key => "recommended_product_id")
end

EShopping/app/models/sub_category.rb
class SubCategory < ActiveRecord::Base
  belongs_to :category
end

EShopping/app/models/track_order.rb
class TrackOrder < ActiveRecord::Base
  belongs_to :order
end

EShopping/app/models/transaction.rb
class Transaction < ActiveRecord::Base
  belongs_to :order
end

EShopping/app/models/used_coupon.rb
class UsedCoupon < ActiveRecord::Base
  belongs_to :user
  belongs_to :order
  belongs_to :coupon
end

EShopping/app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  devise :omniauthable, :omniauth_providers => [:facebook,:google_oauth2,:twitter]
  has_many :cart_items, dependent: :destroy
  has_many :addresses, dependent: :destroy
  has_many :orders, dependent: :destroy
  has_many :order_items, dependent: :destroy
  has_many :wish_lists, dependent: :destroy
  after_create :send_admin_mail
  validates :first_name, presence: true
  validates :last_name, presence: true
  
  def send_admin_mail
    UserMailer.welcome_email(self).deliver
  end

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.email = auth.info.email
      user.password = Devise.friendly_token[0,20]
      user.first_name = auth.info.name   # assuming the user model has a name
    end
  end       
end

EShopping/app/models/wish_list.rb
class WishList < ActiveRecord::Base
  belongs_to :user
  belongs_to :product
end

EShopping/app/controllers/check_outs_controller.rb
class CheckOutsController < ApplicationController
  include CheckOutsHelper
  before_action :authenticate_user!
  before_action :set_total, only: [:index, :review_payment]

  # GET /check_outs
  # GET /check_outs.json
  def index
    @addresses = current_user.addresses
    @address = Address.new
  end

  def review_payment
    @address = Address.find(params[:address_id])
    # helper method review payment
    review_items(@address)
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_total
      @coupon = Coupon.find_by(code: session[:coupon_applied])
      @cart_items = current_user.cart_items
      @sub_total = 0
      @cart_items.each do |item|
        @sub_total += item.quantity * item.product.price
      end
      if @coupon.present?
        @discount = (@sub_total * @coupon.percent.to_i)/100
      else
        @discount = 0
      end
      @cart_total = @sub_total - @discount
      if @cart_total < 5000
        @shipping_cost = 50.to_f
      else
        @shipping_cost = 0.to_f
      end
    end

end

EShopping/app/helpers/brands_helper.rb
module BrandsHelper
end

EShopping/app/helpers/check_outs_helper.rb
module CheckOutsHelper
  def review_items(address)
    if !current_user.addresses.pluck(:id).include?(address.id)
      redirect_to root_path, alert: 'There is no such address'
    elsif address.status == 'inactive'
      redirect_to root_path, alert: 'There is no such address'
    end
  end
end

EShopping/app/helpers/home_helper.rb
module HomeHelper
end

EShopping/app/views/check_outs/_checkout_shipping_total.html.erb
<tr>
  <td>Cart Sub Total</td>
  <td>&#8377; <%= @sub_total %></td>
</tr>
<tr>
  <td>Discount</td>
  <td>- &#8377; <%= @discount %></td>
</tr>
<% @cart_tax=((0.15)*@cart_total).round(2) %>
<tr>
  <td>Service Tax</td>
  <td>&#8377; <%= @cart_tax %></td>
</tr>
<tr class="shipping-cost">
  <td>Shipping Cost</td>
  <td>
    <% if @shipping_cost > 0 %>
      &#8377; <%= @shipping_cost %>
    <% else %>
      <%= 'Free' %>
    <% end %>
  </td>                   
</tr>
<tr>
  <td>Total</td>
  <% @total=@cart_total+@cart_tax+@shipping_cost %>
  <td><span>&#8377; <%= @total %></span></td>
</tr>

EShopping/app/views/check_outs/_form.html.erb
<%= form_for(@check_out) do |f| %>
  <% if @check_out.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@check_out.errors.count, "error") %> prohibited this check_out from being saved:</h2>

      <ul>
      <% @check_out.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

EShopping/app/views/check_outs/_review_order.html.erb
<% if current_user.cart_items.present? %>
  <section id="cart_items">
    <div class="container">
      <div class="step-one">
        <h2 class="heading">Step3 - Review & Payment</h2>
      </div>

      <div class="cart_info">
        <table class="table table-condensed">
          <thead>
            <tr class="cart_menu">
              <td class="image">Item</td>
              <td class="description"></td>
              <td class="price">Price</td>
              <td class="quantity">Quantity</td>
              <td class="total">Total</td>
              <td></td>
            </tr>
          </thead>
          <tbody>
          <% @cart_items.each do |cart_item| %>  
            <tr id="cart-item-delete-<%= cart_item.id %>">
              <td class="cart_product">
                <%= image_tag(cart_item.product.pictures.first.avatar.url,class: 'cart-image') %>
              </td>
              <td class="cart_description">
                <h4><%= cart_item.product.name %></h4>
              </td>
              <td class="cart_price">
                <p>&#8377; <%= cart_item.product.price %></p>
              </td>
              <td class="cart_quantity">
                <div class="cart_quantity_button" id="review-update-<%= cart_item.id %>">
                  <%= number_field_tag :quantity, "#{cart_item.quantity}", min: 1, max: cart_item.product.quantity, product_id: cart_item.product_id, class: 'cart_quantity_input', id: "quantity-update-#{cart_item.id}",disabled: true, remote: true %>
                </div>
              </td>
              <td class="cart_total">
                <% total=cart_item.product.price*cart_item.quantity %>
                <p class="cart_total_price" id="cart-total-<%= cart_item.id %>">&#8377; <%= total %></p>
              </td>
            </tr>
          <% end %>
            <tr>
              <td colspan="4">&nbsp;</td>
              <td colspan="2">
                <table class="table table-condensed total-result" id="checkout-total">
                  <%= render 'check_outs/checkout_shipping_total' %>
                </table>
              </td>
            </tr>
          </tbody>
        </table>
      </div>
    </div>
    <div class="col-sm-offset-5">
      <%= link_to 'Continue To Pay', orders_path(address_id: params[:address_id]), method: :post, class: 'btn btn-width2' %>
    </div>
  </section> <!--/#cart_items-->
<% else %>
  <section id="cart_items">
    <div class="container">
      <div class="cart_info">
        <h2 style="text-align: center;">Your Shopping Bag is Empty</h2>
        <br>
        <h4 style="text-align: center;">Add Product to your cart</h4>
        <br>
        <h4 style="text-align: center;"><%= link_to 'Continue Shopping', root_path, class: 'btn btn-width2' %></h4>
      </div>
    </div>
  </section>
<% end %>

EShopping/app/views/check_outs/_show_address.html.erb
<div id="edit_address">
  <div class="col-sm-12">
    <% @addresses.each do |address| %>
      <% unless address.status == 'inactive' %>
        <div class="col-sm-4">
          <div class="panel panel-default">
            <div class="panel-body">
              <p style="font-size: 20px"><%= address.name %></p>
              <hr>
              <p class="address_para"><%= address.address1 %></p>
              <p class="address_para"><%= address.address2 %></p>
              <p class="address_para"><%= address.pincode %></p>
              <p class="address_para"><%= address.city %></p>
              <p class="address_para"><%= address.state %></p>
              <p class="address_para"><%= address.country %></p>
              <hr>
              <p class="address_para"><%= address.phone %></p>
              <hr>
              <%= link_to 'Deliver to this Address', review_payment_path(address_id: address.id), class: 'btn btn-width2', style: 'margin-left: 60px' %>
              <hr>
              <%= link_to edit_address_path(address), remote: true, style: "color: black" do %>
                <i class="fa fa-pencil-square-o"></i>
                <span>EDIT</span>
              <% end %>
              <%= link_to address_path(address,status: 'off'), method: :put, style: "color: black;margin-left: 180px" do %>
                <i class="fa fa-trash-o"></i>
                <span>DELETE</span>
              <% end %>
            </div>
          </div>
        </div>
      <% end %>
    <% end %>
  </div>
  <div id="new_address" style="margin-left: 30px">
    <%= link_to "Add New Addresss", new_address_path, class: "btn btn-width2", remote: true %>
  </div>
</div>

EShopping/app/views/check_outs/edit.html.erb
<h1>Editing Check Out</h1>

<%= render 'form' %>

<%= link_to 'Show', @check_out %> |
<%= link_to 'Back', check_outs_path %>

EShopping/app/views/check_outs/index.html.erb
<section id="cart_items">
  <div class="container">

    <div class="step-one">
      <h2 class="heading">Step1 - User Detail</h2>
    </div>
    <div class="checkout-options">
      <ul class="nav">
        <li>
          <label><b>LOGIN ID : </b></label>
        </li>
        <li>
          <label><%= current_user.email %></label>
        </li>
        <li>
          <label><b>NAME : </b></label>
        </li>
        <li>
          <label><%= current_user.first_name %></label>
        </li>
      </ul>
    </div><!--/checkout-options-->

    <div class="step-one">
      <h2 class="heading">Step2 - Address</h2>
    </div><!--/register-req-->
    <div class="shopper-informations">
      <% if current_user.addresses.present? %>
        <%= render 'check_outs/show_address' %>
      <% else %>
        <div style="margin-left: 30px">
          <%= link_to "Add New Addresss", new_address_path, class: "btn btn-width2", remote: true %>
        </div>
      <% end %>
    </div>
  </div>
</section> <!--/#cart_items-->

EShopping/app/views/check_outs/new.html.erb
<h1>New Check Out</h1>

<%= render 'form' %>

<%= link_to 'Back', check_outs_path %>

EShopping/app/views/check_outs/review_payment.html.erb
<div id="review-order">
  <%= render 'check_outs/review_order' %>
</div>

EShopping/app/views/check_outs/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_check_out_path(@check_out) %> |
<%= link_to 'Back', check_outs_path %>