demotwitter3/config/routes.rb
Rails.application.routes.draw do
  
  resources :messages
  get 'welcome/index'

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  resources :users do 
    member do
      get :following,:followers
    end
  end
  resources :relationships

  resources :posts do
    get 'images', on: :collection
    resources :comments
  end
  resources :retweets
  root 'welcome#index'

end

demotwitter3/app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    @posts = Post.paginate(:page => params[:page], :per_page => 3)
  	@post = Post.new
  end
end

demotwitter3/app/helpers/welcome_helper.rb
module WelcomeHelper
end

demotwitter3/app/views/welcome/index.html.erb
<div class="col-sm-3">
  <div class = "panel panel-info">
    <div class = "panel-heading">
      <h4>Your Twitter Profile</h4>
      </div>
      <div class = "panel-body">
      <br>
        <% if current_user.avatar.present? %>
          <%= image_tag(current_user.avatar.url(:thumb), class: 'img-rounded') %>
        <% else %>
          <%= image_tag('default.png',size: '100x100',class: 'img-rounded') %>
        <% end %>
          <h4><span class="name"><b><%= current_user.name.capitalize %></b></span> @<%= current_user.username %></h4>
          <br>
          <table class = "table table-bordered">
            <tr>
              <td><%= link_to 'Tweets' ,post_path(current_user) %></td>
              <td><%= link_to 'Followers',followers_user_path(current_user) %></td>
              <td><%= link_to 'Following',following_user_path(current_user) %></td>
            </tr>
            <tr class = "success">
              <td><%= current_user.posts.size %></td>
              <td><%= current_user.followers.count%></td>
              <td><%= current_user.following.count%></td>
            </tr>
          </table>
      </div>
    </div>
    <div class="well">
      <div class="btn-group-vertical btn-block">
        <button type="button" class="btn btn-default user"><%= link_to 'Users',users_path %></button>
        <button type="button" class="btn btn-default user"><%= link_to 'Posts',posts_path %></button>
        <button type="button" class="btn btn-default user"><%= link_to 'Images',images_posts_path %></button>
      </div>
    </div>
</div>
<div class="col-sm-7">
<div class = "panel panel-info">
  <div class = "panel-heading">
  <h3>Post a Tweet</h3>
  </div>
    <br>
    <div class = "panel-body">
    <%= form_for @post, html: { multipart: true } do |f| %>
        <%= f.text_area :content,style: 'border-radius: 10px;',class: 'form-control' %>
        <br><br>
        <%= f.file_field :avatar %>
        <%= f.hidden_field :avatar_cache %>
        <br>
        <%= f.submit "Tweet", class: 'btn btn-primary' %>
    <% end %>
    </div>
</div>
<div class = "panel panel-info">
  <div class = "panel-heading">
    <h3>Public Tweets</h3>
  </div>
  <div class = "panel-body" id="retweets">
  <%= render 'retweets/index' %>
  </div>
</div>
<%= will_paginate @posts %>
</div>
<div class="col-sm-2"></div>